---
- name: System Initialization Configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Collect IaaS information
      ansible.builtin.shell:
        cmd: |-
          set -o pipefail
          set -e
          source /home/tsc/tsc_profile
          tsc --tsc_sysinit --all{% if ntp_server is defined and ntp_server %} --ntp_server={{ ntp_server }}{% endif %}
        executable: /bin/bash
      register: result
      changed_when: false
      failed_when: result.rc != 0

    - name: Display IaaS information
      ansible.builtin.debug:
        msg: '{{ result.stdout }}'
